export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_POST_DATA: 'SET_POST_DATA',
	SET_POST_COMMENT: 'SET_POST_COMMENT',
	DELETE_COMMENT: 'DELETE_COMMENT',
	DELETE_POST: 'DELETE_POST',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_POST_DATA: 'RESET_POST_DATA',
	SET_POSTS: 'SET_POSTS',
	SET_POST_IS_LOADING: 'SET_POST_IS_LOADING',
}
